<?php

use App\Models\DoctorInfo;
use App\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Role;


class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users = [
            [
                'first_name' => 'Abdul',
                'last_name' => 'Kalam',
                'phone_number' => '01680722103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1980-02-10'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-01-01'),
                'address' => 'Airport, Dhaka',
                'email' => 'prn.innovative+owner@gmail.com',
                'password' => '123456789',
                'role' => 'owner',
                'nid' => '12446532665165',
                'salary' => 0,
                'blood_group_id' => '3',
                'organization_id' => '1'
            ],
            [
                'first_name' => 'Rahim',
                'last_name' => 'Uddin',
                'phone_number' => '01680722103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1983-05-10'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2019-02-10'),
                'address' => 'Rampura, Dhaka',
                'email' => 'prn.innovative+admin@gmail.com',
                'password' => '123456789',
                'role' => 'admin',
                'nid' => '12445262665165',
                'salary' => '70000',
                'blood_group_id' => '5',
                'organization_id' => '1'
            ],
            [
                'first_name' => 'Mrs Rozi',
                'last_name' => 'Akhter',
                'phone_number' => '01680722103',
                'gender' => 'female',
                'dob' => Carbon::createFromFormat('Y-m-d', '1973-06-12'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '1997-02-10'),
                'address' => 'Banasree, Dhaka',
                'email' => 'prn.innovative+receptionist@gmail.com',
                'password' => '123456789',
                'role' => 'receptionist',
                'nid' => '12446532321165',
                'salary' => 20000,
                'blood_group_id' => '4',
                'organization_id' => '1'
            ],
            [
                'first_name' => 'Joynul',
                'last_name' => 'Abedin',
                'phone_number' => '01680722103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1971-02-27'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '1997-09-10'),
                'address' => 'Chawlkbazar, Chittagong',
                'email' => 'prn.innovative+doctor@gmail.com',
                'password' => '123456789',
                'role' => 'doctor',
                'doctor_type' => 'indoor',
                'doctor_category' => 'permanent',
                'speciality' => 'neurology',
                'nid' => '12446525965165',
                'salary' => 50000,
                'blood_group_id' => '2',
                'degree' => 'FCPS',
                'designation' => 'Department Head',
                'department_id' => '1',
                'organization_id' => '1',
            ],
            [
                'first_name' => 'John',
                'last_name' => 'Dee',
                'phone_number' => '01680534928',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1994-02-10'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2018-02-15'),
                'address' => 'DC Hill, Chittagong',
                'email' => 'prn.innovative+doctor2@gmail.com',
                'password' => '123456789',
                'role' => 'doctor',
                'doctor_type' => 'indoor',
                'doctor_category' => 'permanent',
                'speciality' => 'Medicine',
                'nid' => '12441115965165',
                'salary' => 100000,
                'blood_group_id' => '1',
                'degree' => 'MBBS',
                'designation' => 'Chairman',
                'department_id' => '2',
                'organization_id' => '1',
            ],
            [
                'first_name' => 'Sudipta',
                'last_name' => 'Dey',
                'phone_number' => '01680722103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1980-02-10'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-02-10'),
                'address' => 'Agrabad, Chittagong',
                'email' => 'prn.innovative+accountant@gmail.com',
                'password' => '123456789',
                'role' => 'accountant',
                'nid' => '12441111594165',
                'salary' => 40000,
                'blood_group_id' => '1',
                'organization_id' => '1'
            ],
            [
                'first_name' => 'Orijit',
                'last_name' => 'Nandy',
                'phone_number' => '01680722103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1998-02-10'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-02-10'),
                'address' => 'Jamalkhan, Chittagong',
                'email' => 'prn.innovative+lab_staff@gmail.com',
                'password' => '123456789',
                'role' => 'lab_staff',
                'nid' => '12441112654165',
                'salary' => 25000,
                'blood_group_id' => '1',
                'organization_id' => '1'
            ],
            [
                'first_name' => 'Sourav',
                'last_name' => 'Chowdhury',
                'phone_number' => '01680722103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '2095-02-10'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-02-10'),
                'address' => 'Rahmothgonj, Chittagong',
                'email' => 'prn.innovative+nurse@gmail.com',
                'password' => '123456789',
                'role' => 'nurse',
                'nid' => '12441113333165',
                'salary' =>35000,
                'blood_group_id' => '1',
                'organization_id' => '1'
            ],
            [
                'first_name' => 'Debjit',
                'last_name' => 'Paul',
                'phone_number' => '01680722103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '2000-02-10'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-02-10'),
                'address' => 'Oxygen, Chittagong',
                'email' => 'prn.innovative+other_staff@gmail.com',
                'password' => '123456789',
                'role' => 'other_staff',
                'nid' => '12441156965165',
                'salary' => 15000,
                'blood_group_id' => '1',
                'organization_id' => '1'
            ],


            [
                'first_name' => 'Rafiq',
                'last_name' => 'Alam',
                'phone_number' => '01614785236',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1992-05-12'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-05-12'),
                'address' => 'Cumilla',
                'email' => 'prn.innovative+rafiq@gmail.com',
                'password' => '123456789',
                'role' => 'owner',
                'salary' => 0,
                'nid' => '12434916765165',
                'blood_group_id' => '3',
                'organization_id' => '2'
            ],
            [
                'first_name' => 'Bakhtiyar',
                'last_name' => 'Uddin',
                'phone_number' => '01680530403',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1980-08-12'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-08-12'),
                'address' => 'Ishkaton, Dhaka',
                'email' => 'prn.innovative+bakhtiyar@gmail.com',
                'password' => '123456789',
                'role' => 'admin',
                'nid' => '12445304625165',
                'salary' => 90000,
                'blood_group_id' => '5',
                'organization_id' => '2'
            ],
            [
                'first_name' => 'Ms Kumkum',
                'last_name' => 'Begum',
                'phone_number' => '01680562049',
                'gender' => 'female',
                'dob' => Carbon::createFromFormat('Y-m-d', '1988-07-18'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-07-18'),
                'address' => 'Panthapath, Dhaka',
                'email' => 'prn.innovative+kumkum@gmail.com',
                'password' => '123456789',
                'role' => 'admin',
                'nid' => '12445309861165',
                'salary' => 75000,
                'blood_group_id' => '3',
                'organization_id' => '2'
            ],
            [
                'first_name' => 'Mrs Fajitul',
                'last_name' => 'Nesa',
                'phone_number' => '01680850493',
                'gender' => 'female',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-01-27'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-01-27'),
                'address' => 'Banasree, Dhaka',
                'email' => 'prn.innovative+fajitul@gmail.com',
                'password' => '123456789',
                'role' => 'receptionist',
                'nid' => '12446532321165',
                'salary' => 30000,
                'blood_group_id' => '4',
                'organization_id' => '2'
            ],
            [
                'first_name' => 'Abul',
                'last_name' => 'Hossain',
                'phone_number' => '01684860503',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1963-10-11'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-10-11'),
                'address' => 'New Market, Chittagong',
                'email' => 'prn.innovative+abul@gmail.com',
                'password' => '123456789',
                'role' => 'doctor',
                'doctor_type' => 'indoor',
                'doctor_category' => 'permanent',
                'speciality' => 'neurology',
                'nid' => '12446525965165',
                'salary' => 85000,
                'blood_group_id' => '6',
                'degree' => 'FCPS',
                'designation' => 'Department Head',
                'department_id' => '1',
                'organization_id' => '2',
            ],
            [
                'first_name' => 'Alamgir',
                'last_name' => 'Hossain',
                'phone_number' => '01680534928',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1974-12-11'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '1994-12-11'),
                'address' => 'DC Hill, Chittagong',
                'email' => 'prn.innovative+alamgir@gmail.com',
                'password' => '123456789',
                'role' => 'doctor',
                'doctor_type' => 'outdoor',
                'doctor_category' => 'on hire',
                'speciality' => 'Medicine',
                'nid' => '12442059965165',
                'salary' => 65000,
                'blood_group_id' => '1',
                'degree' => 'MBBS,PHD',
                'designation' => 'Chairman',
                'department_id' => '3',
                'organization_id' => '2',
            ],
            [
                'first_name' => 'Rony',
                'last_name' => 'Mondol',
                'phone_number' => '01680534928',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1966-12-11'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '1994-12-11'),
                'address' => 'DC Hill, Chittagong',
                'email' => 'prn.innovative+rony@gmail.com',
                'password' => '123456789',
                'role' => 'doctor',
                'doctor_type' => 'outdoor',
                'doctor_category' => 'on hire',
                'speciality' => 'Medicine',
                'nid' => '12442059965165',
                'salary' => 150000,
                'blood_group_id' => '1',
                'degree' => 'MBBS,PHD',
                'designation' => 'Chairman',
                'department_id' => '3',
                'organization_id' => '2',
            ],
            [
                'first_name' => 'Abdul',
                'last_name' => 'Mannan',
                'phone_number' => '01682591003',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1985-05-22'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-05-22'),
                'address' => 'Kapashgola, Chittagong',
                'email' => 'prn.innovative+abdul@gmail.com',
                'password' => '123456789',
                'role' => 'accountant',
                'nid' => '12444059094165',
                'salary' => 50000,
                'blood_group_id' => '5',
                'organization_id' => '2'
            ],
            [
                'first_name' => 'Najim',
                'last_name' => 'Khondokar',
                'phone_number' => '01680036043',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1963-10-24'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-10-24'),
                'address' => 'Lalkhan Bazar, Chittagong',
                'email' => 'prn.innovative+najim@gmail.com',
                'password' => '123456789',
                'role' => 'lab_staff',
                'nid' => '14923612654165',
                'salary' => 55000,
                'blood_group_id' => '8',
                'organization_id' => '2'
            ],
            [
                'first_name' => 'Nandan',
                'last_name' => 'Acharje',
                'phone_number' => '01698745103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1978-02-10'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-02-10'),
                'address' => 'Rajshahi',
                'email' => 'prn.innovative+nandan@gmail.com',
                'password' => '123456789',
                'role' => 'nurse',
                'nid' => '16251113333165',
                'salary' => 35000,
                'blood_group_id' => '6',
                'organization_id' => '2'
            ],
            [
                'first_name' => 'Rukhsana',
                'last_name' => 'Begum',
                'phone_number' => '01758645103',
                'gender' => 'female',
                'dob' => Carbon::createFromFormat('Y-m-d', '1973-07-21'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-07-21'),
                'address' => 'Bagura',
                'email' => 'prn.innovative+rukhsana@gmail.com',
                'password' => '123456789',
                'role' => 'nurse',
                'nid' => '16264923333165',
                'salary' => 30000,
                'blood_group_id' => '5',
                'organization_id' => '2'
            ],
            [
                'first_name' => 'Aman',
                'last_name' => 'Uddin',
                'phone_number' => '01820642103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1967-08-29'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-08-29'),
                'address' => 'Oxygen, Chittagong',
                'email' => 'prn.innovative+aman@gmail.com',
                'password' => '123456789',
                'role' => 'other_staff',
                'nid' => '12360456965165',
                'salary' => 20000,
                'blood_group_id' => '3',
                'organization_id' => '2'
            ],



            [
                'first_name' => 'Md Jakaria',
                'last_name' => 'Rahman',
                'phone_number' => '01853085236',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1996-09-19'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-09-19'),
                'address' => 'Sylhet',
                'email' => 'prn.innovative+jakaria@gmail.com',
                'password' => '123456789',
                'role' => 'owner',
                'salary' => 0,
                'nid' => '12426116765165',
                'blood_group_id' => '3',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Shamshuddin',
                'last_name' => 'Haque',
                'phone_number' => '01682450403',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1992-05-12'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-05-12'),
                'address' => 'Ishkaton, Dhaka',
                'email' => 'prn.innovative+shamshuddin@gmail.com',
                'password' => '123456789',
                'role' => 'admin',
                'nid' => '12120304625165',
                'salary' => 140000,
                'blood_group_id' => '5',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Mrs Khairun',
                'last_name' => 'Nesa',
                'phone_number' => '01826662049',
                'gender' => 'female',
                'dob' => Carbon::createFromFormat('Y-m-d', '1999-07-19'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-07-19'),
                'address' => 'Panthapath, Dhaka',
                'email' => 'prn.innovative+khairun@gmail.com',
                'password' => '123456789',
                'role' => 'admin',
                'nid' => '12105609861165',
                'salary' => 100000,
                'blood_group_id' => '3',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Mrs Bilkis',
                'last_name' => 'Begum',
                'phone_number' => '01680850493',
                'gender' => 'female',
                'dob' => Carbon::createFromFormat('Y-m-d', '1969-12-27'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-12-27'),
                'address' => 'Banasree, Dhaka',
                'email' => 'prn.innovative+bilkis@gmail.com',
                'password' => '123456789',
                'role' => 'receptionist',
                'nid' => '110656532321165',
                'salary' => 45000,
                'blood_group_id' => '4',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Anayet',
                'last_name' => 'Ullah',
                'phone_number' => '01628060503',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1995-10-20'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-10-20'),
                'address' => 'Pathorghata, Chittagong',
                'email' => 'prn.innovative+anayet@gmail.com',
                'password' => '123456789',
                'role' => 'doctor',
                'doctor_type' => 'indoor',
                'doctor_category' => 'permanent',
                'speciality' => 'neurology',
                'nid' => '12406525965165',
                'salary' => 70000,
                'blood_group_id' => '6',
                'degree' => 'FCPS',
                'designation' => 'Department Head',
                'department_id' => '1',
                'organization_id' => '3',
            ],
            [
                'first_name' => 'Jahangir',
                'last_name' => 'Alam',
                'phone_number' => '01680534928',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1970-12-24'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '1994-12-24'),
                'address' => 'DC Hill, Chittagong',
                'email' => 'prn.innovative+jahangir@gmail.com',
                'password' => '123456789',
                'role' => 'doctor',
                'doctor_type' => 'outdoor',
                'doctor_category' => 'on hire',
                'speciality' => 'Medicine',
                'nid' => '12889059965165',
                'salary' => 80000,
                'blood_group_id' => '1',
                'degree' => 'MBBS,PHD',
                'designation' => 'Chairman',
                'department_id' => '3',
                'organization_id' => '3',
            ],
            [
                'first_name' => 'Rakib',
                'last_name' => 'Neshan',
                'phone_number' => '01650634928',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1966-12-13'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '1994-12-13'),
                'address' => 'DC Hill, Chittagong',
                'email' => 'prn.innovative+rakib@gmail.com',
                'password' => '123456789',
                'role' => 'doctor',
                'doctor_type' => 'both',
                'doctor_category' => 'permanent',
                'speciality' => 'Neurology',
                'nid' => '11605959965165',
                'salary' => 120000,
                'blood_group_id' => '1',
                'degree' => 'MBBS,PHD',
                'designation' => 'Assistant Head',
                'department_id' => '3',
                'organization_id' => '3',
            ],
            [
                'first_name' => 'Ishfaq',
                'last_name' => 'Rahman',
                'phone_number' => '01682591003',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1986-05-28'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-05-28'),
                'address' => 'Kapashgola, Chittagong',
                'email' => 'prn.innovative+ishfaq@gmail.com',
                'password' => '123456789',
                'role' => 'accountant',
                'nid' => '11204059094165',
                'salary' => 65000,
                'blood_group_id' => '5',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Amir',
                'last_name' => 'Khasru',
                'phone_number' => '01860536043',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1978-10-24'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-10-24'),
                'address' => 'Shonargaon',
                'email' => 'prn.innovative+amir@gmail.com',
                'password' => '123456789',
                'role' => 'lab_staff',
                'nid' => '11065612654165',
                'salary' => 25000,
                'blood_group_id' => '8',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Babu',
                'last_name' => 'Chowdhury',
                'phone_number' => '01560745103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1980-02-28'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-02-28'),
                'address' => 'Khulna',
                'email' => 'prn.innovative+babu@gmail.com',
                'password' => '123456789',
                'role' => 'nurse',
                'nid' => '16620113333165',
                'salary' => 40000,
                'blood_group_id' => '6',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Khadija',
                'last_name' => 'Khatun',
                'phone_number' => '01758645103',
                'gender' => 'female',
                'dob' => Carbon::createFromFormat('Y-m-d', '1980-02-22'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-02-22'),
                'address' => 'Nilkheth',
                'email' => 'prn.innovative+khadija@gmail.com',
                'password' => '123456789',
                'role' => 'nurse',
                'nid' => '16150923333165',
                'salary' => 35000,
                'blood_group_id' => '5',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Ashiqul',
                'last_name' => 'Islam',
                'phone_number' => '01629445103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1987-07-16'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-07-16'),
                'address' => 'Bagur',
                'email' => 'prn.innovative+ashiqul@gmail.com',
                'password' => '12346789',
                'role' => 'nurse',
                'nid' => '16169223333165',
                'salary' => 40000,
                'blood_group_id' => '5',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Shakhawath',
                'last_name' => 'Uddin',
                'phone_number' => '01840692103',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '1986-08-31'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-08-31'),
                'address' => 'Oxygen, Chittagong',
                'email' => 'prn.innovative+shakhawath@gmail.com',
                'password' => '123456789',
                'role' => 'other_staff',
                'nid' => '12350656965165',
                'salary' => 20000,
                'blood_group_id' => '3',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Sumi',
                'last_name' => 'Banik',
                'phone_number' => '01810652103',
                'gender' => 'female',
                'dob' => Carbon::createFromFormat('Y-m-d', '1999-08-21'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-08-21'),
                'address' => 'Khilgaon',
                'email' => 'prn.innovative+sumi@gmail.com',
                'password' => '123456789',
                'role' => 'other_staff',
                'nid' => '12346056965165',
                'salary' => 40000,
                'blood_group_id' => '3',
                'organization_id' => '3'
            ],
            [
                'first_name' => 'Shohrav',
                'last_name' => 'Hossain',
                'phone_number' => '01826989213',
                'gender' => 'male',
                'dob' => Carbon::createFromFormat('Y-m-d', '2000-02-11'),
                'join_date' => Carbon::createFromFormat('Y-m-d', '2020-02-11'),
                'address' => 'Boalkhali, Chittagong',
                'email' => 'prn.innovative+shohrav@gmail.com',
                'password' => '123456789',
                'role' => 'other_staff',
                'nid' => '12306456965165',
                'salary' => 20000,
                'blood_group_id' => '3',
                'organization_id' => '3'
            ],

        ];

        foreach ($users as $user) {
            $role = Role::where('name', $user['role'])->first();
//            unset($user['role']);
            $u = User::create([
                'first_name' => $user['first_name'],
                'last_name' => $user['last_name'],
                'phone_number' => $user['phone_number'],
                'gender' => $user['gender'],
                'dob' => $user['dob'],
                'join_date' => $user['join_date'],
                'address' => $user['address'],
                'email' => $user['email'],
                'nid' => $user['nid'],
                'salary' => $user['salary'],
                'blood_group_id' => $user['blood_group_id'],
                'password' => $user['password'],
                'organization_id' => $user['organization_id'],
            ]);

            if ($role) {
                $u->assignRole($role);

                if ($role->name === 'doctor') {
                    DoctorInfo::create([
                        'user_id' => $u->id,
                        'degree' => $user['degree'],
                        'designation' => $user['designation'],
                        'doctor_category' => $user['doctor_category'],
                        'doctor_type' => $user['doctor_type'],
                        'speciality' => $user['speciality'],
                        'department_id' => $user['department_id'],
                    ]);
                }
            }
        }
//        $this->command->info("Seeder User Created");
//        DB::table('users')->insert();
    }
}
